### ISSUE TITLE
should nested create operation `query()` return the new row?

### ISSUE THREAD

**Issue by drewfish** [olivierwilkinson/prisma-extension-nested-operations#13]
For root `create` operations, the `await query(args)` returns the newly-created row. Should a nested `create` operation do the same?

Consider this new smoke test ...
```diff
$ git diff test/e2e/smoke.test.ts
diff --git i/test/e2e/smoke.test.ts w/test/e2e/smoke.test.ts
index c48c76d..00779ff 100644
--- i/test/e2e/smoke.test.ts
+++ w/test/e2e/smoke.test.ts
@@ -259,4 +259,48 @@ describe("smoke", () => {
       expect(dbUser.profile).toBeNull();
     });
   });
+
+  it("bug? nested create query() returns new row", async () => {
+    const log: string[] = [];
+    testClient = client.$extends({
+      query: {
+        $allModels: {
+          $allOperations: withNestedOperations({
+            $rootOperation: async ({ operation, model, args, query }) => {
+              const result: any = await query(args);
+              if (operation === 'create') {
+                log.push(`AFTER ${operation} ${model} ${result?.id}`);
+              }
+              return result;
+            },
+            $allNestedOperations: async ({ operation, model, args, query }) => {
+              const result = await query(args);
+              if (operation === 'create') {
+                log.push(`AFTER ${operation} ${model} ${result?.id}`);
+              }
+              return result;
+            },
+          }),
+        },
+      },
+    });
+    const user = await testClient.user.create({
+      data: {
+        email: faker.internet.email(),
+        name: "Sam",
+        profile: {
+          create: { bio: 'I like turtles' },
+        },
+      },
+      include: {
+        profile: true,
+      },
+    });
+    //console.log(user);
+    //console.log(log);
+    expect(log).toEqual([
+      `AFTER create User ${user.id}`,
+      `AFTER create Profile ${user.profile.id}`,
+    ]);
+  });
 });
```

It fails with
```
    - Expected  - 1
    + Received  + 1

      Array [
        "AFTER create User 11",
    -   "AFTER create Profile 7",
    +   "AFTER create Profile undefined",
      ]
```

**Comment by drewfish** [comment]
Hmmm... I did a bunch of `console.log()` debugging, and I think this might be an order-of-operation bug. I -do- see the nested create row in `updatedResult` (from `const updatedResult = await call.result`), but I see that **after** the `await query(args)` has resolved.

**Comment by drewfish** [comment]
I tried `prisma-nested-middleware` and saw the same behavior there.

**Comment by olivierwilkinson** [comment]
Hi there, thanks for raising this!

You've hit upon quite a subtle aspect to the library, this is expected behaviour but there is an alternative to achieve most things requiring response data. There are two main reasons nested queries don't resolve with data:

- whether the data is available is conditional on if there is an include or select for that relation.
- it is not always possible to match the resulting data with a particular call to `query`

The first point I think you probably already realised looking at your smoke test. Originally I set out with the intent to try to return the data when an include was present, but it's not always possible to match up a particular nested query with the results from an include or select. For example an array of nested creates can't be matched up with the included results, or if the include has a where statement the data might not even be available.

While nested queries don't resolve with the included data, if you need to modify the data from an include you can use the `include` or `select` operation type in `allNestedOperations()`.

I think there is information on this in the README, but maybe I'll make it more prominent because this is unexpected behaviour.

Let me know if you have any thoughts or questions, I hope that helps you in what you were trying to achieve!

**Comment by drewfish** [comment]
Thanks! I'm trying to achieve "after create or update" reporting (so not modifying the results). Is the `include` operation type always used for creates? Or can I (do I need to) look in the `scope` to understand whether that `include` is for a newly-created row?

**Comment by olivierwilkinson** [comment]
> Thanks! I'm trying to achieve "after create or update" reporting (so not modifying the results). Is the `include` operation type always used for creates? Or can I (do I need to) look in the `scope` to understand whether that `include` is for a newly-created row?

Ah interesting, I think that is possible in a limited way with this library. It depends on your requirements really!

The best option I can think of using this library is to report the args used to create/update the row after awaiting the query, at that point you know the root query has resolved. This is not ideal in the sense that you would need to manually generate the id before the create calls so they are available to you, and for certain updates that do not take ids you won't have them available. The main problem with using includes is there is not a way to ensure all the results are available to you without breaking some queries (forbidding where for example).

Another issue, which is not possible to get around using extensions, is that any operations that don't use Prisma or use $executeRaw won't be reported.

A rather more difficult but more complete solution is to use an event stream from your database directly. That way you have all the data available to you and don't rely on every query using the ORM. With Postgres you could use Debezium and Kafka, and then write an event processor. There is a decent overview for that architecture in this article: [streaming-data-with-postgresql-kafka-debezium-part-1](https://dev.to/arctype/streaming-data-with-postgresql-kafka-debezium-part-1-4e39).

I hope that is helpful!

**Comment by drewfish** [comment]
Yeah I used to use an event stream from the database (similar to Debezium and Kafka) -- in fact that's what I'm trying to replace because of the operational troubles that has sometimes.

**Comment by drewfish** [comment]
I think I'm able to accomplish what I want, having the nested `operation` `create` passed the row, with the following patch:

```diff
$ git diff src/
diff --git i/src/lib/nestedOperations.ts w/src/lib/nestedOperations.ts
index 4bab695..cdbf0df 100644
--- i/src/lib/nestedOperations.ts
+++ w/src/lib/nestedOperations.ts
@@ -5,7 +5,7 @@ import { OperationCall, NestedParams } from "./types";
 import { extractNestedOperations } from "./utils/extractNestedOperations";
 import { executeOperation } from "./utils/execution";
 import { buildArgsFromCalls } from "./utils/params";
-import { buildTargetRelationPath } from "./utils/targets";
+import { buildTargetRelationPath, isReadTarget } from "./utils/targets";
 import {
   addIdSymbolsToResult,
   getRelationResult,
@@ -108,14 +108,15 @@ export function withNestedOperations<
           return {
             relationsPath,
             updatedResult,
+            isReadTarget: isReadTarget(call.target),
           };
         })
       );

       // keep only the relevant result updates from nested next results
       const resultUpdates = nestedNextResults.filter(
-        (update): update is { relationsPath: string[]; updatedResult: any } =>
-          !!update
+        (update): update is { relationsPath: string[]; updatedResult: any, isReadTarget: boolean } =>
+          !!update && !update.isReadTarget
       );

       resultUpdates
diff --git i/src/lib/utils/targets.ts w/src/lib/utils/targets.ts
index 41155ed..c1e860d 100644
--- i/src/lib/utils/targets.ts
+++ w/src/lib/utils/targets.ts
@@ -100,8 +100,6 @@ export function buildTargetPath(target: Target) {
 }

 export const buildTargetRelationPath = (target: Target): string[] | null => {
-  if (!isReadTarget(target)) return null;
-
   if (target.parentTarget) {
     const basePath = buildTargetRelationPath(target.parentTarget);
     if (!basePath) return null;
```

I don't know if that's a good idea or not 😔 It does pass the smoke tests 🤷

**Comment by olivierwilkinson** [comment]
Ah that is a bummer that you are having problems with your event stream architecture. If the reporting you are doing doesn't need to be immediate you may be able to resolve the operational problems by using snapshots and a daily job to process the events. Obviously I don't know your system or requirements so that may be a no go.

Unfortunately I would say this strategy isn't a good alternative. You may get away with it if you are only concerned with a particular toOne relation, however if that were to change in future you'd have to go back to a similar solution to the one you have already.

If you do want to pursue this avenue regardless I would recommend forking this library, having the nested queries resolve with the include data in only some cases would likely result in a variety of nasty bugs for other users of the library.

**Comment by drewfish** [comment]
Completely understandable re forking -- I had a suspicion that patch would lead to troublesome side effects.

I'll close this issue since it works as designed and documented.
